### ISSUE TITLE
Feature request: More specific error message when you are already connected to Hub

### ISSUE THREAD

**Issue by fabianmakila** [4drian3d/VLobby#3]
Currently if you do /lobby when you are already connected to there it throws the following message:
<img width="688" alt="image" src="https://user-images.githubusercontent.com/44451855/212750718-063fe554-4c70-4f60-846d-0ccc92c915e0.png">

This might let some users think that there was some problem transporting them to hub and not realizing that they are already connected to the hub. Having second configurable error message along the lines "You are already connected to server x" would solve this.

**Comment by EL-S** [comment]
@4drian3d It seems that this fix doesn't work with the command-to-server-handler. However, I have not tested with the regular handler

**Comment by 4drian3d** [comment]
> @4drian3d It seems that this fix doesn't work with the command-to-server-handler. However, I have not tested with the regular handler

In the last commit I just implemented it for the CommandToServer. As you tell me that you have already tested it, despite what you said, everything works correctly?

**Comment by EL-S** [comment]
Yes, sorry about that. My testing was not very comprehensive, so I didn't notice the feature discrepancy at first until I had played for longer! Your latest release has resolved it.
