### ISSUE TITLE
New mode to allow 1:1 commands?

### ISSUE THREAD

**Issue by EL-S** [4drian3d/VLobby#4]
It would be great if there was a mode that allowed 1:1 command and server name pairs

such as

```
# Lobby Commands
commands = ["lobby", "hub"]

[servers]
# Lobby Servers
servers = ["server1", "server2"]
```

Then when a user types /lobby they go to server1, and /hub they go to server2, etc.

**Comment by 4drian3d** [comment]
@EL-S can you test the last commit of the branch `refactor` to see if the function you suggested works correctly?
To activate it, set `command-handler="COMMAND_TO_SERVER"`
